pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                echo('Build Backend')
                dir('api') {
                    withEnv(['NUGET_PACKAGES=D:/Tools/NugetCache']) {
                        bat 'D:/Tools/nuget.exe restore TrackBEE-API.sln'
                        // TODO: change hard coded paths to parametrizable paths ${TOOLS_PATH}

                        script {
                            def msbuild = tool name: 'MSBuild', type: 'hudson.plugins.msbuild.MsBuildInstallation'
                            bat "\"${msbuild}\" TrackBEE-API.sln /p:Configuration=Release /p:Platform=\"Any CPU\""
                            // TODO: add build number /p:ProductVersion=1.0.0.${env.BUILD_NUMBER}
                        }
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo('Test')
            }
        }
        stage('Deploy') {
            steps {
                echo('Deploy')
            }
        }
    }
}
