pipeline { 
    agent any 
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') { 
            steps { 
                echo('Build Backend')
                
                bat '$TOOLS_PATH/nuget.exe restore api/TrackBEE-API.sln'
		        
                script {
                    def msbuild = tool name: 'MSBuild', type: 'hudson.plugins.msbuild.MsBuildInstallation'
                    bat "\"${msbuild}\" api/TrackBEE-API.sln /p:Configuration=Release /p:Platform=\"Any CPU\""
                    // TODO: add build number /p:ProductVersion=1.0.0.${env.BUILD_NUMBER}
                }
            }
        }
        stage('Test'){
            steps {
                echo('Test')
            }
        }
        stage('Deploy') {
            steps {
                echo('Deploy')
            }
        }
    }
}
